project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Deaths of Different Diseases"
  author:
    - Li-Yu Hung (lh3224)
    - Jiayang Liu (jl6680)
  repo-url: https://github.com/CU-MSDS-EDAV-Project/EDAV_Final_16.git #https://github.com/YOUR_GITHUB_ACCOUNT/REPO_NAME
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmos #darkly See other theme @ https://bootswatch.com/
    code-fold: true


