# Conclusion
## Summary
Through our static and dynamic data analysis on diversified dataset resources, we found several exciting phenomena within the short period of 2019 to 2023, a balanced time gap before and after the COVID-19 outbreak. Starting from diseases of similar transmission methods, we found that not all of them follow the same pattern as Covid, nationally or individually, such as influenza. Interestingly, pneumonia matches our expectation that it not only follows the trends but also has a decreasing number of casualties compared to the pandemic. This somewhat confirms our claim that there are some underlying factors that cause people to change their mindset and habits, which as a result is reflected in the deaths of diseases. 

In addition to a specific group of diseases, we extend our proposition to a broader range of diseases such as Septicemia, Malignant neoplasms and so on. We found a similar trend in all diseases when given a fixed date a higher casualty in one disease tends to have higher casualties in others except for “Malignant Neoplasm” and “Combined Covid” which shows a weak correlation between the two.

At the end, we explored the relationship between vaccinations and the total deaths of the diseases. At a high level, we found that the number of vaccinations is high related to the number of deaths for diseases. However, it is hard to tell the causalities between the two merely based on the information we have. However, we can see that due the pandemic the number of vaccinations increases across the years and age groups, which once again confirms our initial hypothesis that after the outbreak of COVID-19, the casualties of diseases drop potentially due to people's changes in mindset and other habits.

## Limitation  
Our exploration suffered from several limitations, including but not confined to missing data, insufficient data, and lack of normalization. As mentioned in the Data Section, a few of the data are missing in all three datasets. Some of them are due to the discrepancy of time collection while others may be caused by variations in data collection. Regardless of the plausible reasons, these are the challenges we encounter during the research. Ideally, we would like to fill in these data either by some estimators such as mean or median. However, due to the time interval the data were collected, it is more reasonable and practical to remove those missing values to avoid any potential misinterpretation given that we are relatively large amounts of datasets. Also, in our exploratory data analysis we mainly use the counts/frequency to compare across various states. However, it would make more sense to compare them after some kind of normalization, such as dividing the frequency by the state population to the density of the death occurrences.  

## Future Direction
In the future, we aim to go into more detail at the regional levels, such as subregions of the national or state level. Since geographical differences may lead to several other factors affecting the death of the diseases. For instance, in our exploration of weekly death counts across the years, we noticed that the number of deaths tends to have a positive relationship with temperature, part of which is caused by geographical variation. However, in this research we are unsure whether there are any changes before and after COVID-19. Similarly transportation, distribution of medical resources and regional customs are all potential factors leading to disease casualties but may have been changed accordingly due to the outbreak. Hence, we need to collect more regional data to follow up on our current studies. 

## Lessons Learned
There are numerous types of graphs we can use to convey similar information and display it given the same set of datasets. The main distinction is that depending on our needs and focus we would prefer one to another, regardless of its interactivity with readers or visibility. For instance, if we want to know about the correlation specifically between two diseases, we will definitely go for scatterplots or biplots rather than fancy parallel coordinate plots. That is to say what matters most in exploratory data analysis is how data is cleaned, processed and displayed. Meanwhile compared to regular R, d3 offers more flexibility and customization to our graphs not only for static graphs but also for interactive dynamic ones. With exposure to d3 in our exploration, we become more aware and capable of the differentiations between the two. 
