# Data

## Description
To find out whether there are any changes to disease casualties and other plausible factors that might also cause the changes, we collected several datasets from Centers for Disease Control and Prevention.  

Data Source 1:  
The first one is "Pneumonia and Influenza Mortality Surveillance" from National Center for Health Statistics (NCHS) Mortality Surveillance System, a table of dimension 19345 by 14 when choosing state data. The data sources are collected by NCHS through State Vital Statistics Offices across the United States. The deaths which is confirmed through death certificate include multiple cause associated with influenza, pneumonia, or COVID. Because the data are collected weekly, they are updated and aggregated by weeks and will be displayed from 1 to 52 through a complete year. Note that the value total deaths include all the frequency based on ICD-10 multiple cause of death so it doesn't equal to the sum of deaths from influenza, pneumonia and COVID-19 only. 

(Plan to import the data)

The link to the data source is as follows:  
https://gis.cdc.gov/grasp/fluview/Mortality.html 

Data Source 2:  
The second one is "Weekly Provisional Counts of Deaths by State and Select Causes, 2020-2023" by National Center for Health Statistics (NCHS), a table of dimension 10477 by 20. The data is collected by NCHS through the Vital Statistics Cooperative Program and updated as of September 27, 2023. The mortality data are based on the death certificates in all the states include counts of death by cause, week and state but they excludes the nonresidents and fetus. Notice that the provisional deaths are based on the flow of the mortality data in the National Vital Statistics System so there is a time lapse between the time deaths occur and the time to submit and eventually reflected on the system. Also, we need to be aware that the cause of the death classification is categorized by ICD-10 codes. So the total values of deaths is not equal to the sum of the listed deaths in other categories. 

(Plan to import the data)

The link to the data source is as follows:  
https://data.cdc.gov/NCHS/Weekly-Provisional-Counts-of-Deaths-by-State-and-S/muzy-jte6 

Data Source 3:  
The final ones are "Weekly Cumulative Influenza Vaccination Coverage, Children 6 months through 18 years, United States" with dimension of 9895 by 28 and "Weekly Cumulative Influenza Vaccination Coverage, Adults 18 and Older United States" with dimension of 4836 by 22 from National Center for Immunization and Respiratory Diseases (NCIRD). The data are updated regularly throughout the flu seasons whenever new data are available. The influenza vaccination coverage is assessed through the National Immunization Survey - Adult COVID Module (NIS-ACM) providing weekly influenza vaccination coverage estimates. Notice that the weekly influenza surveillance report is prepared by the Influenza Division so the data are subject to the changes according the the reports received. 

(Plan to import the data).   

The link to the data source is as follows:  
<18: https://data.cdc.gov/Vaccinations/Weekly-Cumulative-Influenza-Vaccination-Coverage-C/eudc-n39h  
18+: https://data.cdc.gov/Flu-Vaccinations/Weekly-Cumulative-Influenza-Vaccination-Coverage-A/2v3t-r3np.  

(For each data sources, describe how the data are collected and by whom. Describe the format of the data, the frequency of updates, dimensions, and any other relevant information. Note any issues / problems with the data, either known or that you discover. Explain how you plan to import the data. Carefully document your sources with links to the precise data sources that you used. If that is not possible (for example if your data is not available online, then explain that clearly.))

## Research Plan  
Since all data sets are collected weekly, it is intuitive to merge the data across different sources and then group them by states or by weeks in general sense. We may clean and process data by keeping variables indicating weeks, states, ages, and deaths of influenza or/and pneumonia to demonstrate what are the changes before and after the COVID-19 outbreak. Depending on the graphs' needs and availability of data, we could potentially extend the range of data from comparing year 2019 with year 2022 to a wider range of year such as from year 2018 to 2019 and with those from 2021 to 2023. With larger pool of the data points, it is more likely to show the effects of COVID-19 on the casualties of diseases of interest.  

After examining the trends of specific diseases, it is reasonable to apply the same logic to other diseases of interest. However, instead of comparing before and after disease outbreak individually, we are comparing horizontally across different kinds of disease to show how the total deaths spread out in different categories using heatmaps of 10 including one with total casualties as a reference while each of rest is representing a category and its death frequency.  

Although alert of the risks for assorted disease casualties is a good start, we still need some kinds to actions to combat or counteract with such situations. The most common solution to such challenges is through immunization. We would like to discover the correlation between vaccine coverage and deaths. According to our common sense and public education on vaccination, we would expect to have a negative relationship. However, it remains to be verified by a scatter plot of vaccination coverage versus casualties of different diseases grouped by states so we would have each point representing a state with a specific kind of disease. 

(Explain in detail how your data will enable you to answer your research questions from the introduction: 1 page)

## Missing value analysis  
After brief observation on the data sets, we realized that all the data sets have some kinds of missing values which will affect the our result analysis. They are shown in the following aspects:

In dataset 1, we noticed that there are specific weeks of some states that have missing values. For example, in week 46 Alaska, Delaware, District of Columbia, Indiana, Kentucky, Louisiana, Montana, Nevada and North Carolina are all showing "insufficient data". Meanwhile, Nevada is missing all the data for the year 2023 from week 40 to week 46.

In dataset 2, a lot of diseases have null values different states such as Alaska, Arkansas, Colorado, Connecticut, Delaware, District of Columbia, Hawaii, Idaho, Indiana, Iowa, Kansas, Louisiana, Maine, Maryland, Minnesota, most of which are missing in influenza and pneumonia, and abnormal clinical findings. 

In dataset 3, it seems that Guam in "Weekly Cumulative Influenza Vaccination Coverage for Children" tends to have missing values for a few estimation variables such as point estimate, and confidence intervals while the data belongs to "Up-to-date" indicator label in "Weekly Cumulative Influenza Vaccination Coverage for Adults" are highly likely to appear missing. 

(Describe any patterns you discover in missing values. If no values are missing, graphs should still be included showing that: 2 graphs plus commentary)
